name: First GitHub Action

on:
  push:

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'

      - name: Show Python version
        run: python --version

      - name: Run Python app
        run: python app/test.py